files:
  - source: README.md
    translation: /%two_letters_code%/%two_letters_code%/%two_letters_code%/index.php
    languages_mapping:
      two_letters_code:
        en: ..
  - source: '*.php'
    translation: /%two_letters_code%/%two_letters_code%/%two_letters_code%/index.php
